version: "3.9"

networks:
    laravel_network:
        driver: bridge

services:
    laravel-php:
        image: gitlab.ekl.tn:5050/pfe_devops/laravel/eklxpartners-php:latest
        container_name: laravel-php
        networks:
            - laravel_network
        expose:
            - "9000"
        volumes:
            - laravel_data:/var/www/laravel
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=laravel
            - DB_USERNAME=root
            - DB_PASSWORD=rootpassword
        command: >
            sh -c "php artisan storage:link || true &&
            	     php artisan migrate:fresh --seed &&
                   php-fpm"
        restart: unless-stopped

    laravel-nginx:
        image: gitlab.ekl.tn:5050/pfe_devops/laravel/eklxpartners-php:latest
        container_name: laravel-nginx
        networks:
            - laravel_network
        ports:
            - "80:80"
        depends_on:
            - laravel-php
            - mysql
        volumes:
            - laravel_data:/var/www/laravel
        restart: unless-stopped

    mysql:
        image: mysql:5.7
        container_name: mysql
        networks:
            - laravel_network
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: laravel
        volumes:
            - mysql_data:/var/lib/mysql
        expose:
            - "3306"
        restart: unless-stopped

    mailpit:
        image: axllent/mailpit
        container_name: mailpit
        networks:
            - laravel_network
        ports:
            - "8025:8025"
            - "1025:1025"
        restart: unless-stopped

volumes:
    laravel_data:
    mysql_data:
